### ISSUE TITLE
如可使用代理？？

### ISSUE THREAD

**Issue by a88wyzz** [c0re100/BahamutAnimeDownloader#10]
有没有相关的参数？

**Comment by c0re100** [comment]
> 有没有相关的参数？

export/set HTTP_PROXY=http://127.0.0.1:5000

**Comment by a88wyzz** [comment]
在dos命令行中如何加载代理参数？

**Comment by c0re100** [comment]
> 在dos命令行中如何加载代理参数？

不清楚你在問甚麼
在CMD輸入`export HTTP_PROXY=blahhhhhhhh........` / `set HTTP_PROXY=blahhhhhhhh........` 不就可以了.......?
