### ISSUE TITLE
Something happened - Ads not away?

### ISSUE THREAD

**Issue by a88wyzz** [c0re100/BahamutAnimeDownloader#11]
![QQ图片20190710231136](https://user-images.githubusercontent.com/35162785/60981005-1e318980-a368-11e9-8442-963a6ac8aebd.png)

如图这是什么问题？？？

**Comment by rniczh** [comment]
我剛試著"暫時性"的解決這個問題 PR: #12 
我把時間拉長到原本廣告(Ad)的時間(30秒)，解決了這件事情，

看起來是巴哈母特這幾天改變了他們處理Ad的方式

**Comment by c0re100** [comment]
https://github.com/c0re100/BahamutAnimeDownloader/releases/tag/1.4
廣告問題已修正。

**Comment by sakuraakira** [comment]
這三天參考了 c0re100 的原始檔
寫了一個C# Windows 的版本
https://github.com/sakuraakira/AniGamerDownloader
希望能多多交流
