### ISSUE TITLE
有些動畫似乎無法下載

### ISSUE THREAD

**Issue by tonyhsie** [c0re100/BahamutAnimeDownloader#13]
例如 新妹魔王的契約者
https://ani.gamer.com.tw/animeVideo.php?sn=11049

![圖片 2019-07-24 20-06-54](https://user-images.githubusercontent.com/52758827/61792198-bcd0e680-ae4e-11e9-92ac-e78849de27c2.png)

其它新番都正常，不曉得是不是巴哈對舊番的處理方式有什麼地方跟新番不同

另外，這個程式非常好用，謝謝!

**Comment by miyouzi** [comment]
這是限制級動畫要求登陸，即需要提供cookie

**Comment by tonyhsie** [comment]
原來如此，謝謝解惑了!

**Comment by tonyhsie** [comment]
再請問一下
搭配 cookie.txt 使用後發現，要先在網頁端播完廣告之後，anidownloader 才能下載
請問這個現象正常嗎?

![圖片 2019-07-24 21-05-28](https://user-images.githubusercontent.com/52758827/61795899-fe658f80-ae56-11e9-936e-e3ad976d73b2.png)

如圖

前兩次使用 anidownloader 都失敗
之後先到動畫瘋網站播放此影片，並等待廣告播畢，這時再使用 anidownloader 就成功了

**Comment by miyouzi** [comment]
這個程式在設計上，似乎把提供cookie直接看作擁有VIP，不進行廣告等待而導致的問題。
```https://ani.gamer.com.tw/ajax/token.php``` 這個 API 有返回相關賬戶資訊（json格式），通過這個來判斷是否是VIP比較好。

一般情況返回：
```
{'src': '', 'animeSn': 103211, 'r18': 3, 'vip': True, 'time': 1, 'login': 1, 'promote': []}
```

遇到錯誤返回：
```
{'error': {'code': 1016, 'message': '本作為限制級，須登入您的巴哈帳號！', 'status': '', 'details': []}}
```

需要等待作者更新

**Comment by c0re100** [comment]
https://github.com/c0re100/BahamutAnimeDownloader/releases/tag/1.5
