### ISSUE TITLE
cookies问题

### ISSUE THREAD

**Issue by a88wyzz** [c0re100/BahamutAnimeDownloader#15]
![QQ截图20190727155801](https://user-images.githubusercontent.com/35162785/61991797-107a4480-b088-11e9-9c43-094fc8006939.jpg)
之前朋友给的cookie是能下载到1080p，最近却不能下载，怎么回事呢?
如果不用cookie的话是可以下载到720p的

**Comment by miyouzi** [comment]
動畫瘋的 cookie 過8小時就會更新。

**Comment by a88wyzz** [comment]
朋友给的cookie都是我找他要，他马上给我抓取的，何来超过8小时，之前是可以使用的，最近是不行~~~

**Comment by miyouzi** [comment]
這個時間是從上次cookie更新開始計算，而不是從抓取時開始計算。

舉個例子：
朋友的cookie是在0點刷新的，朋友7點抓cookie給你，你9點才使用，那麽此時這個cookie已經過期。

或者你的意思是朋友cookie可用，抓取后你馬上使用遇到的問題？

**Comment by c0re100** [comment]
Wait....raw cookie不能有空行....
有一個 `\r` 所以解析不到

**Comment by c0re100** [comment]
fixed: https://github.com/c0re100/BahamutAnimeDownloader/releases/tag/1.5.1
