### ISSUE TITLE
cookie不会自动刷新

### ISSUE THREAD

**Issue by a88wyzz** [c0re100/BahamutAnimeDownloader#17]
AniDownloader.exe加载cookie后，不会自动刷新cookie，而aniGamerPlus运行后却可以自动刷新，不必担心cookie会过期，不知道AniDownloader能否添加此功能~~~

因为aniGamerPlus没有下载进度显示，看着不舒服，目前都是用aniGamerPlus刷新cookie后，用AniDownloader.exe加载再下载~~~

**Comment by lleeopen** [comment]
因为aniGamerPlus没有下载进度显示，看着不舒服，目前都是用aniGamerPlus刷新cookie后，用AniDownloader.exe加载再下载~~~

**Comment by rniczh** [comment]
@lleeopen  之後有空的話我會再來看看怎麼用，不過最近很忙，你也可以看看怎麼用然後提個PR

**Comment by a88wyzz** [comment]
我的意思是，AniDownloader加载cookie后，先检测更新一下cookie，然后再进行下载~~~

下面是aniGamerPlus的程序运行日志: 可以参考一下
2019-08-11 10:07:39 檢查更新 檢查更新成功
2019-08-11 10:07:39 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v14.1 
2019-08-11 10:07:39 工作目錄: F:\aniGamerPlus_v14.1 
2019-08-11 10:07:39 開始更新 
2019-08-11 10:07:39 讀取cookie 發現cookie檔案
2019-08-11 10:07:39 讀取cookie 已讀取cookie
2019-08-11 10:07:40 收到新cookie: sn=12640 
2019-08-11 10:07:40 新cookie保存成功 
2019-08-11 10:07:40 新cookie保存成功 
2019-08-11 10:07:40 用戶cookie已更新 
2019-08-11 10:07:40 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2019-08-11 10:07:40 更新终了

**Comment by c0re100** [comment]
v1.6已支援自動更新Cookie
如果與網頁使用相同的Cookie，網頁版應該會自動登出的，請重新登入吧LOL

https://github.com/c0re100/BahamutAnimeDownloader/releases/tag/1.6

**Comment by miyouzi** [comment]
@c0re100  cookie的刷新与UA有關，要求与登陸時的UA相同，我看了下commit，UA是定死的windows chrome，需要注意。

**Comment by c0re100** [comment]
> @c0re100 cookie的刷新与UA有關，要求与登陸時的UA相同，我看了下commit，UA是定死的windows chrome，需要注意。

Ummm
瀏覽器頻密更新的關係，要相同UA的話不太可能，除非巴哈不檢查版本號碼
Cookie大概多少個小時更新一次? 我等下次Cookie更新再進行測試

__我先暫時重開這個issue__
如果出現cookie問題，麻煩到這個issue反映

**Comment by miyouzi** [comment]
@c0re100 大概8小時刷新一次，之前碰到過這個坑，詳見這個 [issue](https://github.com/miyouzi/aniGamerPlus/issues/2)

我的做法是開放UA給用戶設定了，默認 Windows chrome

另外瀏覽器版本好像沒有嚴格要求一致（畢竟不會設計成用戶升級瀏覽器就強制登出），主要是 OS 和 瀏覽器類型（FireFox/Chrome）

**Comment by a88wyzz** [comment]
![QQ截图20191101200409](https://user-images.githubusercontent.com/35162785/68023669-d0f47180-fce2-11e9-82a4-9493cfbf5a58.jpg)

最新1.6版本，看日志，还是不能更新cookie，还是说过期~~~

aniGamerPlus却可以自动更新cookie~~

![QQ截图20191101200548](https://user-images.githubusercontent.com/35162785/68023718-0731f100-fce3-11e9-824d-f70ec8f29c50.jpg)

**Comment by a88wyzz** [comment]
最新1.6的下载不正常，好像是提示广告跳不过去，换回1.5的正常下载~~~

![QQ截图20191101231201](https://user-images.githubusercontent.com/35162785/68034681-1756ca00-fcfd-11e9-9fd2-131150823dab.jpg)

**Comment by c0re100** [comment]
> 最新1.6的下载不正常，好像是提示广告跳不过去，换回1.5的正常下载~~~
> 
> ![QQ截图20191101231201](https://user-images.githubusercontent.com/35162785/68034681-1756ca00-fcfd-11e9-9fd2-131150823dab.jpg)

已修正未登入問題
https://github.com/c0re100/BahamutAnimeDownloader/releases/tag/1.6.1

**Comment by c0re100** [comment]
> ![QQ截图20191101200409](https://user-images.githubusercontent.com/35162785/68023669-d0f47180-fce2-11e9-82a4-9493cfbf5a58.jpg)
> 
> 最新1.6版本，看日志，还是不能更新cookie，还是说过期~~~
> 
> aniGamerPlus却可以自动更新cookie~~
> 
> ![QQ截图20191101200548](https://user-images.githubusercontent.com/35162785/68023718-0731f100-fce3-11e9-824d-f70ec8f29c50.jpg)

本身cookie就已經無效了，所以無法更新......
cookie更新只有一次機會，所以再更新的話就會無效
只有最新的cookie才能繼續更新下去

**Comment by tonyhsie** [comment]
現在使用無痕模式獲取 cookie 可以順利下載影片
但隔天再次下載就會說 cookie 過期了（Set Cookie failed - Seems your cookie is expired.）
只得再次重新手動更新 cookie

請問這樣是正常的情況嗎?

**Comment by miyouzi** [comment]
@tonyhsie 可以説明一下你是什麽系統，以及獲取cookie用的是什麽瀏覽器嗎？

**Comment by tonyhsie** [comment]
> @tonyhsie 可以説明一下你是什麽系統，以及獲取cookie用的是什麽瀏覽器嗎？

Windows 10 v1909 專業版，Chrome 瀏覽器
