### ISSUE TITLE
Bahamut Anime Downloader V2

### ISSUE THREAD

**Issue by c0re100** [c0re100/BahamutAnimeDownloader#18]
Finished:
- [x] Login
- [x] Refresh cookie/token if needed
- [x] Auto login if cookie expired/deleted
- [x] Get Video Title
- [x] 2-Step Verification
- [x] Support multi episode download(Queueing)

Todo:
- [ ] Web UI
- [ ] Configuration and more........(?)

ETA: Unknown

**Comment by YFTX2015** [comment]
合并功能希望增加TS格式。

**Comment by c0re100** [comment]
DISCONTINUED.
