### ISSUE TITLE
exe偵測有毒

### ISSUE THREAD

**Issue by softbearlolz** [c0re100/BahamutAnimeDownloader#19]
https://www.virustotal.com/gui/file/13c4148c73875f847051441e0c034a30e6e8b2e98e6505199c221a1099175a5d/detection

一開始windows defender報毒 
後來直接把檔案丟上去掃的

**Comment by c0re100** [comment]
> https://www.virustotal.com/gui/file/13c4148c73875f847051441e0c034a30e6e8b2e98e6505199c221a1099175a5d/detection
> 
> 一開始windows defender報毒
> 後來直接把檔案丟上去掃的

又誤判了.......加入白名單就好了
基本上大多數防毒都會誤判Go的`Stripped binary`
因沒有特徵的關係，然後只能當成病毒處理。
詳細可看看 #2
