### ISSUE TITLE
exe偵測有毒

### ISSUE THREAD

**Issue by Bofutw** [c0re100/BahamutAnimeDownloader#2]
02.02.2019 19.31.49
物件名稱: RiskTool.Win32.BitCoinMiner.jwsh
請問這是正常的嗎???

**Comment by c0re100** [comment]
.........................?
請問是那一個防毒軟件偵測出來的............wtf??????????
virustotal 全部都沒有問題...........
Windows: https://www.virustotal.com/#/file/e0fa5b628f2c2a3cf9b111f17666a84515afc5f22f64e7f311ca96c3e1c22b1c/detection
Linux: 
https://www.virustotal.com/#/file/5a5d1b69459239c473970af7c386d28cf6bfde0b3ad860be6d63de28a8538ea5/detection
Mac:
https://www.virustotal.com/#/file/71a28c20d2876ab7bacd1fc7bb7cd9ac67fe68c956d6c20177f5c8d28f149bdd/detection

**Comment by Bofutw** [comment]
我是卡巴斯基掃的欸 但我進去看virustotal 裡面的卡巴寫clean XDD

**Comment by c0re100** [comment]
> 我是卡巴斯基掃的欸 但我進去看virustotal 裡面的卡巴寫clean XDD

你先對一對sha256 hash?
下載[HashMyFile](https://www.nirsoft.net/utils/hash_my_files.html)
然後將`AniDownloader.exe`放進去
再看看是不是與virustotal的sha256一樣

**Comment by Bofutw** [comment]
不一樣喔 我這邊載下來的是
SHA256: CEC362A5EEFA21116A526AD73B7F321B7FD2910A7C57330F86419FB6A29B6732

**Comment by c0re100** [comment]
> 不一樣喔 我這邊載下來的是
> SHA256: CEC362A5EEFA21116A526AD73B7F321B7FD2910A7C57330F86419FB6A29B6732

咦 忘記了我本地的檔案有修改過...
不過 CEC362A5EEFA21116A526AD73B7F321B7FD2910A7C57330F86419FB6A29B6732 也沒有卡巴這個問題....
https://www.virustotal.com/#/file/cec362a5eefa21116a526ad73b7f321b7fd2910a7c57330f86419fb6a29b6732/detection

可以試一試這個版本嗎?
https://drive.google.com/open?id=1BqkAWkjI7hPyqH5J753_6Nw7Qu3orxGT

**Comment by Bofutw** [comment]
CEC362A5EEFA21116A526AD73B7F321B7FD2910A7C57330F86419FB6A29B6732 
這版我上傳virustotal上面的卡巴也是寫clean 但在自己電腦上掃就會有問題

然後下面這個版本掃完沒事~~

**Comment by c0re100** [comment]
> CEC362A5EEFA21116A526AD73B7F321B7FD2910A7C57330F86419FB6A29B6732
> 這版我上傳virustotal上面的卡巴也是寫clean 但在自己電腦上掃就會有問題
> 
> 然後下面這個版本掃完沒事~~

-s disable symbol table
```
export GOOS=windows
go build -ldflags "-s" -o release/AniDownloader.exe
```
有問題的是用 `-s`
沒問題就是沒用 `-s`
不知道卡巴在玩甚麼.............
不過很明顯誤判了 或者  病毒特徵庫沒更新 (?)
