### ISSUE TITLE
這兩天突然無法下載了

### ISSUE THREAD

**Issue by tonyhsie** [c0re100/BahamutAnimeDownloader#20]
回報一個問題

上次下載成功是 3 天前，今天要下載就失敗了

![圖片 2020-05-15 03-01-23](https://user-images.githubusercontent.com/52758827/81974941-df8bf000-9658-11ea-8423-0fdca5f0de2b.png)

好像是廣告時間從 8 秒延長到 20 秒的關係

再麻煩作者有空確認一下了，感謝!

**Comment by rniczh** [comment]
I try to fix this in #21

**Comment by c0re100** [comment]
Fixed.
v1.6.2~
https://github.com/c0re100/BahamutAnimeDownloader/releases/tag/release-1.6.2
