### ISSUE TITLE
m3u8 list 出現問題

### ISSUE THREAD

**Issue by Lorne0** [c0re100/BahamutAnimeDownloader#22]
`No need refresh cookie.
Gained access.
You're Premium user
Adaway.
Get m3u8 playlist.
Your choice: 1080p
Create m3u8 playlist failed - open tmp15417/hdntl=exp=1589897148~acl=%2f*~data=-------PC~hmac=c05ce9f930bb02e4994023797f0b115928cf488f8f7544256b3310bc7d42e9a4/chunklist_b5000000.m3u8: no such file or directory`
使用 cookie 無法下載
使用瀏覽器看 m3u8 list 會出現 Access Denied

**Comment by YFTX2015** [comment]
![屏幕截图(1)](https://user-images.githubusercontent.com/12757305/82241299-7bc23980-996e-11ea-8597-afa0caa965c6.png)
我的是这样，动画疯解析系统貌似更新了。

**Comment by c0re100** [comment]
巴哈好像改回原來的樣子了....
PS: @YFTX2015 https://github.com/c0re100/BahamutAnimeDownloader/releases/tag/release-1.6.2

**Comment by rniczh** [comment]
我剛試著去載了一次，在我這看起來沒問題。 @YFTX2015 你是用目前最新的嗎？ 
![image](https://user-images.githubusercontent.com/4802296/82365074-bbf2ec00-9a42-11ea-9039-04995c8728fa.png)

**Comment by YFTX2015** [comment]
出问题时还用的是老版本，现在换成新的就对了。昨天暂时用VideoDownloadHelper撑过去了，这个倒是一直有效，只不过下载速度死慢。

**Comment by c0re100** [comment]
> 我剛試著去載了一次，在我這看起來沒問題。 @YFTX2015 你是用目前最新的嗎？
> ![image](https://user-images.githubusercontent.com/4802296/82365074-bbf2ec00-9a42-11ea-9039-04995c8728fa.png)

在早上的時候，我看到是query string改動了
`xxxx.m3u8?hdntl=exp={unix_timestamp}...........`
但非會員沒這個問題，有cookie情況下才會
我猜大概是巴哈將未改好的改動deploy到production，然後revert了
還是先等他們改好再處理吧

**Comment by YFTX2015** [comment]
现在用新版本，即使是会员Cookie也能正常下载了。

**Comment by love57232** [comment]
今天使用出現了錯誤 昨天都正常 謝謝 2020/08/05 23:11:01 Something happened - Ads not away?
