### ISSUE TITLE
今天使用的時候出現了Ads not away?的錯誤 可能有改了

### ISSUE THREAD

**Issue by love57232** [c0re100/BahamutAnimeDownloader#23]
今天使用出現了錯誤 昨天都正常 謝謝  可能又改秒數了 2020/08/05 23:11:01 Something happened - Ads not away?

**Comment by rniczh** [comment]
確實是秒數改了，我再調一下

**Comment by love57232** [comment]
好的 辛苦您了 感謝!!

**Comment by love57232** [comment]
不好意思 想請問這個要從哪邊修改呢 因為之前是用exe來抓比較多 只有用過cookie的指令 這個還不太會用.. 謝謝您

**Comment by rniczh** [comment]
@love57232 目前還沒被作者merge，也還沒釋出執行檔，如果你要用的要自己compile了，在我發pr的那個branch那

**Comment by love57232** [comment]
好的 目前有嘗試在您今天新發布的main.go 做修改了 想請問我該如何觸發像您說的./AniDownloader -t 28 -s 16486 to specify the waiting time is 28 seconds.
Otherwise, the default time duration becomes 30 seconds currently.

這部分呢 謝謝

**Comment by rniczh** [comment]
@love57232  在資料夾下 `make deps` 安裝需要的package，再執行 `make` 會編譯出執行檔，之後就是上面那個指令了

**Comment by love57232** [comment]
好的 我再嘗試看看 謝謝 第一次用這部分挺多不太明白的QQ

**Comment by c0re100** [comment]
https://github.com/c0re100/BahamutAnimeDownloader/releases/tag/release-1.6.3
已更新至1.6.3
