### ISSUE TITLE
要怎麼下載cookie文件

### ISSUE THREAD

**Issue by kache0** [c0re100/BahamutAnimeDownloader#25]
我去google上找了一個插件來下載cookie
結果error一直跳出Please try again - format not corret, Allow: numeric / URL
抱歉 這問題可能有點蠢

**Comment by rniczh** [comment]
可以看一下你是 1. 用什麼插件以及 2. 怎麼使用在 downloader 的嗎？

**Comment by kache0** [comment]
> 可以看一下你是 1. 用什麼插件以及 2. 怎麼使用在 downloader 的嗎？

https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid 
我把cookie檔案下載下來丟進去程式的資料夾,然後打開並輸入AniDownloader -q 1080p -c cookie.txt -s 19336
最後就會閃退,error檔顯示Please try again - format not corret, Allow: numeric / URL

**Comment by rniczh** [comment]
我用了你提供的插件也出現其他問題，不過看起來是 cookie 前面內容造成的。
你可以試試用這個插件：https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg
不過要注意的是，在這個插件的設定裡，記得要把 export format 改成 Netscape format
![image](https://user-images.githubusercontent.com/4802296/101588163-b8e03d00-3a20-11eb-90e8-e068e561a4c9.png)

**Comment by kache0** [comment]
> 我用了你提供的插件也出現其他問題，不過看起來是 cookie 前面內容造成的。
> 你可以試試用這個插件：https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg
> 不過要注意的是，在這個插件的設定裡，記得要把 export format 改成 Netscape format
> ![image](https://user-images.githubusercontent.com/4802296/101588163-b8e03d00-3a20-11eb-90e8-e068e561a4c9.png)

還是不能 他還是會跳出Please try again - format not corret, Allow: numeric / URL 格式改過了

**Comment by rniczh** [comment]
@kache0 雖然有點久了，那應該是你 -s 後面的數字有問題導致的，可能是因為打成全形之類的造成的。

**Comment by kache0** [comment]
雖然已經沒在用了 不過還是非常謝謝你的回答
