### ISSUE TITLE
chrome 登入巴哈付費帳密，下載器偵測不到，都只能720P下載。

### ISSUE THREAD

**Issue by abc30359** [c0re100/BahamutAnimeDownloader#26]
如題。
感覺沒有去Google Chrome的Cookies取的資訊？？？

**Comment by aaronlin0122** [comment]
Cookies 要自己獲取。
F12 開啟 Chrome開發工具 到 Network 選 ani.gamer.tw 並復製 Headers 下方的 Cookies，
接著到項目底下建立名為 cookies.txt 的檔案並將 剛才復製好的 Cookies 填入保存。
![113481693-cd24cb80-944f-11eb-911f-3b1a3719512f](https://user-images.githubusercontent.com/5726473/113490307-c8b5ec80-94fb-11eb-8288-bba81952f117.png)

執行時記得填上選項 使用 cookies.txt 並下載 1080 解析度
`AniDownloader -c cookies.txt -q 1080p`
