### ISSUE TITLE
沒辦法下載了 應該是改了廣告秒數

### ISSUE THREAD

**Issue by love57232** [c0re100/BahamutAnimeDownloader#28]
輸入編號後過一陣子自動退出  log提示 2021/07/17 01:59:20 Something happened - Where are you from?

**Comment by aaronlin0122** [comment]
請確認你的 ip 是否來自台灣，或者使用 vpn 。

**Comment by love57232** [comment]
> 請確認你的 ip 來自台灣，或者使用 vpn 。

抱歉剛剛確認看了下 log日期看錯了 剛剛測試遇到的情況 輸入後過一下子沒有如期開始 而是直接關閉 也沒有出現錯誤的提示

**Comment by love57232** [comment]
有測試別的方式好像也是一樣
