### ISSUE TITLE
目前是遇到這個錯誤代碼

### ISSUE THREAD

**Issue by love57232** [c0re100/BahamutAnimeDownloader#29]
單純用AniDownloader.exe 大概跑完秒數後會直接閃退 error.log不會有錯誤的提示 但如果用 cmd去叫的話 會出現如下圖的錯誤 有嘗試過-t 去改秒數 但如果短的是ads類的秒數錯誤 28 30是跳這個錯誤
![image](https://user-images.githubusercontent.com/69254947/126365569-31f9447f-910f-4640-96e4-13efd8445e00.png)

**Comment by love57232** [comment]
> 單純用AniDownloader.exe 大概跑完秒數後會直接閃退 error.log不會有錯誤的提示 但如果用 cmd去叫的話 會出現如下圖的錯誤 有嘗試過-t 去改秒數 但如果短的是ads類的廣告秒數錯誤 28 30是跳這個錯誤
> ![image](https://user-images.githubusercontent.com/69254947/126365569-31f9447f-910f-4640-96e4-13efd8445e00.png)

**Comment by aaronlin0122** [comment]
我估計這個項目應該不會繼續維護了，建議你試試隔壁的 [miyouzi/aniGamerPlus](https://github.com/miyouzi/aniGamerPlus)。

**Comment by aaronlin0122** [comment]
懂 BT 的話，也可以用 [c0re100/qBittorrent-Enhanced-Edition](https://github.com/c0re100/qBittorrent-Enhanced-Edition) 這個防吸血的 BT 客戶端，去 [動漫花園](https://share.dmhy.org/topics/list/sort_id/2) 載番。

**Comment by love57232** [comment]
好的 謝謝您
