### ISSUE TITLE
有時候下載過程會有部分片段被關閉連線

### ISSUE THREAD

**Issue by i1itione** [c0re100/BahamutAnimeDownloader#4]
會顯示像這樣的訊息：

Retrying - media_b2000000_50.ts
media_b2000000_12.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=139, ErrCode=NO_ERROR, debug=""

Retrying - media_b2000000_66.ts
media_b2000000_11.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=139, ErrCode=NO_ERROR, debug=""

因此最終 mux 出的影片檔就會缺少了沒有下載到的片段。

而如果重新下載一次或多試幾次就有可能順利完整下載，
不過因為前一次的檔案片段會在 mux 之後自動清除，
變成每次重新下載的時候，皆需重新從第一個片段下載。

**Comment by rniczh** [comment]
@i1itione 
這個問題我是把handler.go中 cleanUp() 的RemoveAll h.tmp那段註解掉
```go
func (h *bahamut) cleanUp() {
    // Delete a temporary directory
    // os.RemoveAll(h.tmp)
    fmt.Println("Cleaned up.")
    fmt.Println(fmt.Sprintf("Total time: %ds", time.Now().Unix()-h.startTime))
}
```
然後你下載完後你在確認看看是不是真的沒有那個檔案, 
因為實際上它失敗後它會重新下載
```go
time.Sleep(500 * time.Millisecond)
h.downloadChunk(chuckUrl)
```

如果真的沒有可以接續這樣改：
由於他是把時間當作tmp檔案片段的資料夾的檔名
所以我把download.go中的 downloadM3U8() 把原本的h.tmp的命名方式給註解掉
換成：h.tmp = "tmp-" + h.sn
這樣每次的資料夾名稱就會固定了

```go
func (h *bahamut) downloadM3U8() {
    // Create a temporary directory for storing
    // h.tmp = "tmp" + strconv.FormatInt(time.Now().Unix(), 10)
    h.tmp = "tmp-" + h.sn
    os.Mkdir(h.tmp, 0755)
    ...
```
因為註解掉了這個部份, 所以還要把上面 import的 strconv給註解掉, 因為沒有用到了
不然會compile不過
```go
import (
    ...
    // "strconv"
    ...
)
```

效果大概會是這樣, 即便刪除了其中某個ts, 再下載一次時只會下載沒有的部份
![2019-02-09_18-33](https://user-images.githubusercontent.com/4802296/52519718-f47e1480-2c9a-11e9-9bbe-8749f095a9a3.png)

**Comment by c0re100** [comment]
> @i1itione
> 這個問題我是把handler.go中 cleanUp() 的RemoveAll h.tmp那段註解掉
> 
> ```go
> func (h *bahamut) cleanUp() {
>     // Delete a temporary directory
>     // os.RemoveAll(h.tmp)
>     fmt.Println("Cleaned up.")
>     fmt.Println(fmt.Sprintf("Total time: %ds", time.Now().Unix()-h.startTime))
> }
> ```
> 
> 然後你下載完後你在確認看看是不是真的沒有那個檔案,
> 因為實際上它失敗後它會重新下載
> 
> ```go
> time.Sleep(500 * time.Millisecond)
> h.downloadChunk(chuckUrl)
> ```
> 
> 如果真的沒有可以接續這樣改：
> 由於他是把時間當作tmp檔案片段的資料夾的檔名
> 所以我把download.go中的 downloadM3U8() 把原本的h.tmp的命名方式給註解掉
> 換成：h.tmp = "tmp-" + h.sn
> 這樣每次的資料夾名稱就會固定了
> 
> ```go
> func (h *bahamut) downloadM3U8() {
>     // Create a temporary directory for storing
>     // h.tmp = "tmp" + strconv.FormatInt(time.Now().Unix(), 10)
>     h.tmp = "tmp-" + h.sn
>     os.Mkdir(h.tmp, 0755)
>     ...
> ```
> 
> 因為註解掉了這個部份, 所以還要把上面 import的 strconv給註解掉, 因為沒有用到了
> 不然會compile不過
> 
> ```go
> import (
>     ...
>     // "strconv"
>     ...
> )
> ```
> 
> 效果大概會是這樣, 即便刪除了其中某個ts, 再下載一次時只會下載沒有的部份
> ![2019-02-09_18-33](https://user-images.githubusercontent.com/4802296/52519718-f47e1480-2c9a-11e9-9bbe-8749f095a9a3.png)

當初我寫的時候是因為巴哈在使用隨機密鑰，並不是固定的(巴哈改版了好幾次啦.....)
而且當時我也想寫resumable功能，針對這個隨機密鑰問題
不過因時間關係，所以沒有實現這個功能~~

現在改回用同一條密鑰的話，我可以改回用sn當作資料夾名稱
至於重試失敗，我要看看如何解決.......

**Comment by i1itione** [comment]
> > @i1itione
> > 這個問題我是把handler.go中 cleanUp() 的RemoveAll h.tmp那段註解掉
> > ```go
> > func (h *bahamut) cleanUp() {
> >     // Delete a temporary directory
> >     // os.RemoveAll(h.tmp)
> >     fmt.Println("Cleaned up.")
> >     fmt.Println(fmt.Sprintf("Total time: %ds", time.Now().Unix()-h.startTime))
> > }
> > ```
> > 
> > 
> > 然後你下載完後你在確認看看是不是真的沒有那個檔案,
> > 因為實際上它失敗後它會重新下載
> > ```go
> > time.Sleep(500 * time.Millisecond)
> > h.downloadChunk(chuckUrl)
> > ```
> > 
> > 
> > 如果真的沒有可以接續這樣改：
> > 由於他是把時間當作tmp檔案片段的資料夾的檔名
> > 所以我把download.go中的 downloadM3U8() 把原本的h.tmp的命名方式給註解掉
> > 換成：h.tmp = "tmp-" + h.sn
> > 這樣每次的資料夾名稱就會固定了
> > ```go
> > func (h *bahamut) downloadM3U8() {
> >     // Create a temporary directory for storing
> >     // h.tmp = "tmp" + strconv.FormatInt(time.Now().Unix(), 10)
> >     h.tmp = "tmp-" + h.sn
> >     os.Mkdir(h.tmp, 0755)
> >     ...
> > ```
> > 
> > 
> > 因為註解掉了這個部份, 所以還要把上面 import的 strconv給註解掉, 因為沒有用到了
> > 不然會compile不過
> > ```go
> > import (
> >     ...
> >     // "strconv"
> >     ...
> > )
> > ```
> > 
> > 
> > 效果大概會是這樣, 即便刪除了其中某個ts, 再下載一次時只會下載沒有的部份
> > ![2019-02-09_18-33](https://user-images.githubusercontent.com/4802296/52519718-f47e1480-2c9a-11e9-9bbe-8749f095a9a3.png)
> 
> 當初我寫的時候是因為巴哈在使用隨機密鑰，並不是固定的(巴哈改版了好幾次啦.....)
> 而且當時我也想寫resumable功能，針對這個隨機密鑰問題
> 不過因時間關係，所以沒有實現這個功能~~
> 
> 現在改回用同一條密鑰的話，我可以改回用sn當作資料夾名稱
> 至於重試失敗，我要看看如何解決.......

會出現下載失敗（被關閉連線）有可能是因為下載速度過快的問題嗎？
如果是的話，限速下載也許能解決？

**Comment by c0re100** [comment]
> > > @i1itione
> > > 這個問題我是把handler.go中 cleanUp() 的RemoveAll h.tmp那段註解掉
> > > ```go
> > > func (h *bahamut) cleanUp() {
> > >     // Delete a temporary directory
> > >     // os.RemoveAll(h.tmp)
> > >     fmt.Println("Cleaned up.")
> > >     fmt.Println(fmt.Sprintf("Total time: %ds", time.Now().Unix()-h.startTime))
> > > }
> > > ```
> > > 
> > > 
> > > 然後你下載完後你在確認看看是不是真的沒有那個檔案,
> > > 因為實際上它失敗後它會重新下載
> > > ```go
> > > time.Sleep(500 * time.Millisecond)
> > > h.downloadChunk(chuckUrl)
> > > ```
> > > 
> > > 
> > > 如果真的沒有可以接續這樣改：
> > > 由於他是把時間當作tmp檔案片段的資料夾的檔名
> > > 所以我把download.go中的 downloadM3U8() 把原本的h.tmp的命名方式給註解掉
> > > 換成：h.tmp = "tmp-" + h.sn
> > > 這樣每次的資料夾名稱就會固定了
> > > ```go
> > > func (h *bahamut) downloadM3U8() {
> > >     // Create a temporary directory for storing
> > >     // h.tmp = "tmp" + strconv.FormatInt(time.Now().Unix(), 10)
> > >     h.tmp = "tmp-" + h.sn
> > >     os.Mkdir(h.tmp, 0755)
> > >     ...
> > > ```
> > > 
> > > 
> > > 因為註解掉了這個部份, 所以還要把上面 import的 strconv給註解掉, 因為沒有用到了
> > > 不然會compile不過
> > > ```go
> > > import (
> > >     ...
> > >     // "strconv"
> > >     ...
> > > )
> > > ```
> > > 
> > > 
> > > 效果大概會是這樣, 即便刪除了其中某個ts, 再下載一次時只會下載沒有的部份
> > > ![2019-02-09_18-33](https://user-images.githubusercontent.com/4802296/52519718-f47e1480-2c9a-11e9-9bbe-8749f095a9a3.png)
> > 
> > 
> > 當初我寫的時候是因為巴哈在使用隨機密鑰，並不是固定的(巴哈改版了好幾次啦.....)
> > 而且當時我也想寫resumable功能，針對這個隨機密鑰問題
> > 不過因時間關係，所以沒有實現這個功能~~
> > 現在改回用同一條密鑰的話，我可以改回用sn當作資料夾名稱
> > 至於重試失敗，我要看看如何解決.......
> 
> 會出現下載失敗（被關閉連線）有可能是因為下載速度過快的問題嗎？
> 如果是的話，限速下載也許能解決？

不是, 有很多原因導致連線中斷

**Comment by c0re100** [comment]
https://github.com/c0re100/BahamutAnimeDownloader/releases/tag/release-1.2.0

嗯，我知道為甚麼會這樣了，所以重寫過重試部分
你可以試試還會不會缺少某部份的片段

**Comment by i1itione** [comment]
> https://github.com/c0re100/BahamutAnimeDownloader/releases/tag/release-1.2.0
> 
> 嗯，我知道為甚麼會這樣了，所以重寫過重試部分
> 你可以試試還會不會缺少某部份的片段

media_b2000000_991.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
Retrying - media_b2000000_991.ts
<nil>
media_b2000000_981.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
Retrying - media_b2000000_981.ts
media_b2000000_980.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
Retrying - media_b2000000_980.ts
media_b2000000_989.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
Retrying - media_b2000000_989.ts
<nil>
media_b2000000_993.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
Retrying - media_b2000000_993.ts
<nil>
<nil>
<nil>
<nil>
<nil>
 997 / 1014 [===============================================================================================>-]  98.32%<nil>
<nil>
<nil>
<nil>
<nil>
<nil>
 1014 / 1014 [============================================================================================] 100.00% 46s
Merging chunk file...please wait a moment...
File location: output/11042.mp4
Cleaned up.

我用 11042 這個影片來測試，不過我還沒有確認最終 mux 出來的影片是否仍缺少部分片段。

**Comment by c0re100** [comment]
> > https://github.com/c0re100/BahamutAnimeDownloader/releases/tag/release-1.2.0
> > 嗯，我知道為甚麼會這樣了，所以重寫過重試部分
> > 你可以試試還會不會缺少某部份的片段
> 
> media_b2000000_991.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
> Retrying - media_b2000000_991.ts
> 
> media_b2000000_981.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
> Retrying - media_b2000000_981.ts
> media_b2000000_980.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
> Retrying - media_b2000000_980.ts
> media_b2000000_989.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
> Retrying - media_b2000000_989.ts
> 
> media_b2000000_993.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
> Retrying - media_b2000000_993.ts
> 
> 
> 
> 
> 
> 997 / 1014 [===============================================================================================>-] 98.32%
> 
> 
> 
> 
> 
> 1014 / 1014 [============================================================================================] 100.00% 46s
> Merging chunk file...please wait a moment...
> File location: output/11042.mp4
> Cleaned up.
> 
> 我用 11042 這個影片來測試，不過我還沒有確認最終 mux 出來的影片是否仍缺少部分片段。

每個片段是2秒
segments 980*2的話 = 32分40秒-33分2秒之間會有缺少問題
檢查一下這段時間就可以了

**Comment by i1itione** [comment]
> > > https://github.com/c0re100/BahamutAnimeDownloader/releases/tag/release-1.2.0
> > > 嗯，我知道為甚麼會這樣了，所以重寫過重試部分
> > > 你可以試試還會不會缺少某部份的片段
> > 
> > 
> > media_b2000000_991.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
> > Retrying - media_b2000000_991.ts
> > media_b2000000_981.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
> > Retrying - media_b2000000_981.ts
> > media_b2000000_980.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
> > Retrying - media_b2000000_980.ts
> > media_b2000000_989.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
> > Retrying - media_b2000000_989.ts
> > media_b2000000_993.ts save failed - http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
> > Retrying - media_b2000000_993.ts
> > 997 / 1014 [===============================================================================================>-] 98.32%
> > 1014 / 1014 [============================================================================================] 100.00% 46s
> > Merging chunk file...please wait a moment...
> > File location: output/11042.mp4
> > Cleaned up.
> > 我用 11042 這個影片來測試，不過我還沒有確認最終 mux 出來的影片是否仍缺少部分片段。
> 
> 每個片段是2秒
> segments 980*2的話 = 32分40秒-33分2秒之間會有缺少問題
> 檢查一下這段時間就可以了

影片看起來正常，應該是沒有缺少片段了。
也確認了下載過程中 tmp 資料夾裡的檔案數量，有全部的片段沒錯。

感謝修正下載問題。
