### ISSUE TITLE
想要輸出ts檔的話要怎麼修改?

### ISSUE THREAD

**Issue by junjxie** [c0re100/BahamutAnimeDownloader#6]
我把handler.go裡的mp4都改為ts之後編譯

可以成功輸出ts檔，但是用potplayer查影片資訊

發現都至少小於mp4版本一個影格 請問這是正常的嗎

TS版的秒數也會比mp4版的少一秒

mp4版的則跟線上看顯示的秒數相同

是不是ffmpeg的輸出指令也要更改 求指導m(_  _)m

![image](https://i.imgur.com/2LAJ2zg.png)
![image](https://i.imgur.com/qEJ9YZs.png)
![image](https://i.imgur.com/DG8Tuax.png)

**Comment by rniczh** [comment]
我試了一下你提供的影片，frames數一致的耶
![2019-04-25_23-16](https://user-images.githubusercontent.com/4802296/56747381-6f41d080-67b0-11e9-8ed1-4f6ae83a687c.png)


而秒數就是右邊顯示的：9:59.95

而在我的播放器(mpv) 上面兩邊都是顯示10分鐘
![2019-04-25_23-09_1](https://user-images.githubusercontent.com/4802296/56747220-2427bd80-67b0-11e9-9205-c5932a7c4b90.png)

**Comment by junjxie** [comment]
請問contributor大大是修改handler.go之後輸出ts的嗎
我這邊測試同影片的720p mp4依然多一幀,ts少一幀

**Comment by rniczh** [comment]
@penjune  是的, 我只是把handler.go在merge那邊把mp4改成ts而已

我檢查frames的指令是：
`ffmpeg -i  11796.mp4   -map 0:v:0 -c copy -f null -`

**Comment by c0re100** [comment]
720p ts和mp4都一樣14400
![14400](https://user-images.githubusercontent.com/5726473/56806619-01a0ad80-685f-11e9-8028-a76bb8255d94.png)
然後........windows就顯示10:00和09:59(都是windows的錯
![windows的錯](https://user-images.githubusercontent.com/5726473/56806401-6576a680-685e-11e9-8eef-4f11c35c807c.png)

**Comment by junjxie** [comment]
謝謝兩位的協助
依照你們的指令
幀數確實都相同
我再研究看看potplayer跟windows為什麼會顯示錯誤orz
