### ISSUE TITLE
請問在linux環境下怎麼安裝跟運作

### ISSUE THREAD

**Issue by junjxie** [c0re100/BahamutAnimeDownloader#7]
不太熟linux orz
目前使用的是debian 9
編譯完之後bash顯示
cannot execute binary file
請問要怎麼解決?

**Comment by c0re100** [comment]
> 不太熟linux orz
> 目前使用的是debian 9
> 編譯完之後bash顯示
> cannot execute binary file
> 請問要怎麼解決?

你可以使用預編譯版
https://github.com/c0re100/BahamutAnimeDownloader/releases

`wget https://github.com/c0re100/BahamutAnimeDownloader/releases/download/release-1.2.1/AniDownloader_Linux`
`chmod 755 AniDownloader_Linux`
`./AniDownloader_Linux`

**Comment by junjxie** [comment]
感謝 已測試成功
原來要用./的方式執行orz

**Comment by junjxie** [comment]
我目前使用的是新加坡節點
請問有推薦的代理嗎

**Comment by c0re100** [comment]
> 我目前使用的是新加坡節點
> 請問有推薦的代理嗎

免費是最貴的, 所以..........
亦有一些付費的被封了 你要自己找找.......

**Comment by junjxie** [comment]
作者您的預編譯版可以在代理下運行
但是我自編譯的沒辦法走代理路線 請問有什麼原因嗎orz
我讓cli走代理的方式是修改~/.bashrc
export http_proxy="socks5://127.0.0.1:1080"
export https_proxy="socks5://127.0.0.1:1080"
export ftp_proxy="socks5://127.0.0.1:1080"
新增這三行 然後source ~/.bashrc

截圖如下:
![image](https://i.imgur.com/5QSvyA2.png)

**Comment by c0re100** [comment]
你的Go太舊不支援http_proxy(Socks5)，只支援http(s)的http_proxy
請改用proxychains/tsocks等代理軟件

**Comment by junjxie** [comment]
感謝您的建議
我最後選擇的是privoxy，轉發socks5到http
alias son='export http_proxy=http://127.0.0.1:8118 && export https_proxy=http://127.0.0.1:8118'
alias sof='unset http_proxy && unset https_proxy'
新增這兩行 然後source ~/.bashrc

測試結果如下，再次感謝您的協助 m(_ _)m
![image](https://i.imgur.com/2pJeeod.png)
