### ISSUE TITLE
部分番劇bug

### ISSUE THREAD

**Issue by junjxie** [c0re100/BahamutAnimeDownloader#8]
大部分是2000年以前放送的

sn = 9821, 1353 還有按照放送年代排列的總列表最後一頁的好幾部都是
遇到這類番劇都會無法parse m3u8

有三種畫質
360p = 540x360
480p = 720x480
576p = 864x576

看起來只有parser.go跟handler.go需要修改
不過360p的部分由於跟一般番劇有重疊
所以這類舊番360p的下載指令可能需要定義一個新的?

**Comment by rniczh** [comment]
簡單的修一下，目前看來這樣是能解決

handler.go
![2019-05-03_21-03](https://user-images.githubusercontent.com/4802296/57139254-54421280-6de7-11e9-8bf5-b56554d779b4.png)

parser.go
![2019-05-03_21-03_1](https://user-images.githubusercontent.com/4802296/57139256-54daa900-6de7-11e9-8e0a-26f9fda01e52.png)

main.go
![2019-05-03_21-04](https://user-images.githubusercontent.com/4802296/57139257-54daa900-6de7-11e9-9218-d0e07369345e.png)

**Comment by junjxie** [comment]
我原本還多設一個360v2來存540x360
看來是我想太多了XD

已測試成功
